name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # todos los días a medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        with:
          github_user_name: miguelavilaipc
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist
          git commit -m "generate contribution snake" || echo "No changes to commit"
          git push
